# Generated by Django 4.1.6 on 2023-02-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Text",
        ),
    ]
