# Generated by Django 4.1.6 on 2023-02-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_delete_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="numbers",
            field=models.IntegerField(default=0),
        ),
    ]
