# Generated by Django 4.1.6 on 2023-02-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_choice_numbers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="numbers",
        ),
    ]
